---
- hosts: k8smaster
  become: true
  tasks:
    - name: Check if .kube directory exist
      ansible.builtin.stat:
        path: /home/localadmin/.kube
      register: kubeDir
    
    - name: Debug kubeDir
      ansible.builtin.debug:
        msg: "{{ kubeDir.stat }}"

    - name: Initialize the cluster
      ansible.builtin.shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16
      become: true
      become_user: localadmin
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      when: not kubeDir.stat.exists

    - name: Create .kube directory
      become: true
      become_user: localadmin
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: '0755'

    - name: Copies admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/localadmin/.kube/config
        remote_src: true
        owner: localadmin

    - name: Install Pod network
      become: true
      become_user: localadmin
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
      args:
        chdir: $HOME

    - name: Get the token for joining the worker nodes
      become: true
      become_user: localadmin
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

        #    - debug:
        #      msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: true
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
